[package]
name = "wasmer-template-renderer"
version = "0.1.0"
authors = ["arashpaknezad"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
handlebars = "3.4.0"
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]